---
- name: 'Install package'
  become: true
  apt:
    pkg: 'ntp'
    state: 'present'
    cache_valid_time: 3600
    update_cache: true
    install_recommends: false

- name: 'Ensure configuration'
  become: true
  template:
    src: 'ntp.conf.j2'
    dest: '/etc/ntp.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'Restart NTPd'
